# Generated by Django 3.2.1 on 2021-05-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institutes',
            table='institutes',
        ),
    ]
