# Generated by Django 3.2.1 on 2021-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_institutes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='activation_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
