# Generated by Django 3.2.1 on 2021-05-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='status',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.status'),
        ),
    ]
